### ISSUE TITLE
Despite using Bundler's verificationGasLimit, the error "AA40 over verificationGasLimit" persists

### ISSUE THREAD

**Issue by oneleo** [pilagod/waallet-extension#55]
I observed that in this code snippet, when estimating the verificationGasLimit value, having paymasterAndData leads to a smaller value than not having it. This frequently causes the Bundler to return the "AA40 over verificationGasLimit" error during transaction submission. [Original code](https://github.com/pilagod/waallet-extension/blob/46bd4007db11a5b8549250452b3543a40fcfec83/tabs/userOperationAuthorization.tsx#L68-L72)

**Comment by pilagod** [comment]
Fixed by #124
