### ISSUE TITLE
Show user operation details in history

### ISSUE THREAD

**Issue by pilagod** [pilagod/waallet-extension#60]
Currently we leverage etherscan to get the transaction history, without further details. It could be better to show history by user operation details.

**Comment by oneleo** [comment]
Development Steps:
1. Pass the `Storage Interface` to the `Provider` and, upon successful transaction submission by the `Provider`, store `transactionHash`, `userOpHash` and `userOp` in Storage.
2. Eliminate the `Storage Interface` passed to the `Provider`. After a successful transaction submission by the `Provider`, emit an event containing `transactionHash`, `userOpHash`, and `userOp`. Components interested in this event, such as the `transactionHistory` component, can subscribe to it. Upon receiving the event, the `transactionHistory` component stores `transactionHash`, `userOpHash`, and `userOp` in Storage.
